server:
  port: 8082
#  tomcat:
#    threads:
#      max: 25
#    accept-count: 25
#    max-connections: 100
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
  sentinel:
    enabled: true # 将FeignClient作为Sentinel的簇点资源
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城购物车服务接口文档"
    desc: "黑马商城购物车服务接口文档"
    package: com.hmall.cart.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 # sentinel的控制台地址
      http-method-specify: true # 是否设置请求方式作为资源名称